# Generated by Django 2.2 on 2019-04-20 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SUCCESS STORY', 'SUCCESS STORY'), ('FUNDING', 'FUNDING'), ('STARTUP', 'STARTUP'), ('WOMEN', 'WOMEN ENTERPRENEURS'), ('TECH', 'TECH'), ('ART AND CULTURE', 'ART AND CULTURE')], default='SUCCESS STORY', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo_post', models.ImageField(upload_to='post_pics/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
